Add some resources to Readme
Concurrent-Vertex/Solidity-Beginner-to-Advanced pull request #5
Opened 2021-10-07 02:44 UTC by ldotto46

2021-10-07 05:04 UTC, PratikGarai submitted a review, later dismissed

2021-10-07 05:10 UTC, PratikGarai requested changes

2021-10-07 05:10 UTC, PratikGarai commented on README.md
> +## 🔍 Cryptography
@ldotto46  Can you kindly change the attached links under this section to open the English version by default?

2021-10-07 05:10 UTC, PratikGarai commented on README.md
> +
Optional : Include section for links to deployment tools (remix, truffle, etc)

2021-10-07 17:16 UTC, ldotto46 commented on README.md
> +## 🔍 Cryptography
Yes! let me change it

2021-10-09 00:47 UTC, PratikGarai requested changes
Some links invalid

2021-10-09 00:47 UTC, PratikGarai commented on README.md
> +- [What is a SHA-256](https://academy.bit2me.com/en/que-es-hash/)
sha256 link takes to page describing "hash"

2021-10-09 00:47 UTC, PratikGarai commented on README.md
> +- [HASH](https://academy.bit2me.com/en/que-es-hash//)
invalid link

2021-10-14 16:30 UTC, merged